# Generated by Django 5.0.2 on 2024-11-30 23:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "protocol_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("description", models.TextField()),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("species", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "pain_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("animal_count", models.IntegerField(default=0)),
                (
                    "funding_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="protocols/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("is_example", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("is_new_submission", models.BooleanField(default=False)),
                ("iacuc_approval", models.BooleanField(default=False)),
                ("safety_approval", models.BooleanField(default=False)),
                ("compliance_notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtocolStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="standards/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
