# Generated by Django 5.0.2 on 2024-11-30 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("search", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="laboratory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="users.lab",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_protocols", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="protocolreview",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="search.protocol",
            ),
        ),
        migrations.AddField(
            model_name="protocolreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="protocolstandard",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_standards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
